Feature/m3 game logic
jubaan/m__oop__tic-tac-toe pull request #3
Opened 2020-02-10 22:12 UTC by didymus707

Milestone 3: Game logic completed

2020-02-11 18:18 UTC, imhta requested changes
# Changes required 🛑 

### Hello  @didymus707 @jubaan  , 👋 You have done a great job in this project 👏 

* [x] The application should detect a sequence of three vertical elements that are equal

![image](https://user-images.githubusercontent.com/25448577/74265717-0b7d9980-4d29-11ea-8f49-8b1ac3fdb9fd.png)




----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

2020-02-11 18:22 UTC, jubaan commented
> # Changes required stop_sign
> ### Hello @didymus707 @jubaan , wave You have done a great job in this project clap
> 
>     * [x]  The application should detect a sequence of three vertical elements that are equal
> 
> 
> ![image](https://user-images.githubusercontent.com/25448577/74265717-0b7d9980-4d29-11ea-8f49-8b1ac3fdb9fd.png)
> ### Don't forgot to request for another code review
> 
> **Pon Muthu Selvam N**
> **[nponmuthuselvam@gmail.com](mailto:nponmuthuselvam@gmail.com)**
> _If you have any queries, feel free to ping me on slack_

Hi @imhta thanks for your review... I'm running the game but I can't get that error. This is what I get if get the marks in vertical line. 

![image](https://user-images.githubusercontent.com/25774518/74266009-2ae4da00-4cc9-11ea-9cac-4a0299536e76.png)

2020-02-11 18:25 UTC, jubaan commented
Could you be kindly enough to guide me, so I can replicate this error

2020-02-11 18:25 UTC, didymus707 commented
I was about saying the same thing @jubaan . The game works well... See below
![ttt](https://user-images.githubusercontent.com/38667458/74266250-44efde00-4d04-11ea-80cc-c5b44ba7ce0e.png)

2020-02-11 18:33 UTC, didymus707 commented
Tried using some invalid options to check the game but it still works fine
![ttt1](https://user-images.githubusercontent.com/38667458/74266882-571e4c00-4d05-11ea-8dbb-dabaa31a1b7a.png)
![trying the invalid errors](https://user-images.githubusercontent.com/38667458/74266887-5a193c80-4d05-11ea-89b4-743ce6c1337b.png)

2020-02-11 18:54 UTC, imhta commented
@didymus707 @jubaan Most of the times it is working fine but if I am doing in a random way, it breaks don't know why? find and try to fix that.  below image represents all the input given to break the game.

![image](https://user-images.githubusercontent.com/25448577/74268372-c60f9b00-4d2d-11ea-88c6-df42a888a684.png)

2020-02-11 18:57 UTC, jubaan commented
> @didymus707 @jubaan Most of the times it is working fine but if I am doing in a random way, it breaks don't know why? find and try to fix that. below image represents all the input given to break the game.
> 
> ![image](https://user-images.githubusercontent.com/25448577/74268372-c60f9b00-4d2d-11ea-88c6-df42a888a684.png)

Thanks a lot! We'll work on it, to see whats wrong!

2020-02-11 20:28 UTC, jubaan commented
> @didymus707 @jubaan Most of the times it is working fine but if I am doing in a random way, it breaks don't know why? find and try to fix that. below image represents all the input given to break the game.
> 
> ![image](https://user-images.githubusercontent.com/25448577/74268372-c60f9b00-4d2d-11ea-88c6-df42a888a684.png)

Thank you @imhta we could duplicate the error, and now the programs works at it suppose to.

2020-02-11 21:03 UTC, didymus707 commented
Winning match fixed

2020-02-11 21:36 UTC, Forison requested changes
### Status: Require changes🛑
## 🙋‍♂️ team
good job on addressing changes associated with the behavior of the application🙂 raised in the previous review.
Here are some other issues to address to get the project approved🙂
* [ ] No puts/print and get.chomp outside main.rb file ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

* [ ] It is better and cleaner to house each class in its own file and then use require_relative to import them when the need arises.
### That is it, kindly make these changes and submit the project for review
#### Happy coding💻
#### Addo Forison

2020-02-11 21:39 UTC, Forison commented on bin/main.rb
> +puts "\n" + '*' * 50
👉 this part of the code can be housed in another file and imported into main. Main should only serve as an entry point for your app execution🙂

2020-02-13 08:09 UTC, didymus707 commented
Milestone 3: All review changes made

2020-02-14 01:17 UTC, Forison requested changes
### Status: REquire changes🛑
## 🙋‍♂️ TEAM,
you have done a good job on this one so far,
Here are a few issues we have to address to get this project approved.🙂
* [x] The game has to end immediately there is a winner. currently, this what I get after winning👇
![Screenshot from 2020-02-13 12-53-17](https://user-images.githubusercontent.com/29695661/74492657-9da6ae80-4e9d-11ea-8c52-57ed96c92ed0.png)

* [x] The game should inform players of a draw. Currently, this what I get when there is a draw.👇
![Screenshot from 2020-02-13 12-55-06](https://user-images.githubusercontent.com/29695661/74492641-941d4680-4e9d-11ea-8e37-7cbd758199c9.png)

### [optional]
You make split the classes in the logic file to three different files. This makes the code more readable.
## That is it kindly make these changes and submit the project for review.🙂
#### Happy coding
#### Addo Forison

2020-02-14 05:45 UTC, fatymahmed approved these changes
## Hi @jubaan @didymus707 
Your game works, great job on that 👏👏.
 - Remember you shouldn't have puts/print and get.chomp outside `main.rb` file, that means your logic shouldn't have them!. Please fix this before merging [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) 


### It's a 👍🏾 from me!
## ✔️ Approved!
Good luck with your next projects.
 _Don't forget to submit your project completion form_
_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

2020-02-14 05:46 UTC, fatymahmed commented on lib/board.rb
> +      print '> '
- `print` and `puts` shouldn't be used here.

2020-02-14 05:47 UTC, fatymahmed commented on lib/board.rb
> +      choices << choice
- `gets.chomp` shouldn't be used here

2020-02-14 12:16 UTC, closed without merging