Feature/rspec testing
jubaan/m__oop__tic-tac-toe pull request #6
Opened 2020-02-19 18:49 UTC by jubaan

1st rspec review

2020-02-19 19:25 UTC, jubaan commented
The linter error is from another application not frome the sticker linter.

2020-02-19 20:58 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments on your code. 👇 

- [ ] Ensure your specs cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) Example: if there is a test for player2 will return player2 mark:
```ruby
it 'returns player1 mark' do
   player1 = Player.new('player1')
   expect(player1.mark).to eql('+')
end
```
There should also be a spec for the negative scenario:
```ruby
it 'returns player1 mark' do
   player1 = Player.new('player1')

   expect(player1.mark).to eql('+')
   expect(player1.mark).not_to eql('/')
end
```

**Kindly submit for another code review request once these issues have been fixed.** _Happy coding!_ 🎉

2020-02-19 20:58 UTC, suretrust commented on spec/game_logic_spec.rb
> +    end
Context should be inside a describe block, not the other way around.  See guidelines [here](https://github.com/rubocop-hq/rspec-style-guide#context-cases).

2020-02-19 20:58 UTC, suretrust commented on spec/game_logic_spec.rb
> +  end
- Specs for each method should be wrapped in one `describe` block.

2020-02-20 13:07 UTC, didymus707 commented
Testing for Tic Tac Toe: All review changes made

2020-02-20 19:42 UTC, didymus707 commented
Linter fix caused all tests to fail... All tests are passing

2020-02-20 21:51 UTC, Forison approved these changes
## Status:Approved💚 ,
# Hi@ Team🙌,
 Good job 👏👏 on addressing the changes raised in the previous review.
 The tests look good.
> My opinion on the usage of context: to add to what was said in the previous review. Context is used for more readability of the test. For instance, when you are testing a method that has ie a positive or negative behavior or etc... use context to wrap each scenario that way you have one context of method wrap in one context and the other in another context... When there is one context i don't think it is neccessary to use context
#### Happy coding
#### Addo Forison

2020-02-20 22:09 UTC, merged